"use client"

import type React from "react"

import { createContext, useContext, useEffect, useState } from "react"

// Define available languages
export type Language = "en" | "ro"

// Define the context type
type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => { },
  t: (key) => key,
})

// Define translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Language
    "language.select": "English",

    // Dashboard
    dashboard: "Dashboard",
    "dashboard.description": "Overview of your business",
    "dashboard.totalCustomers": "Loyal Customers",
    "dashboard.receiptsProcessed": "App Scans",
    "dashboard.pointsAwarded": "Points Awarded",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.vsPreviousMonth": "vs. previous month",
    "dashboard.revenue": "Revenue",
    "dashboard.revenueOverview": "Daily revenue overview",
    "dashboard.engagementRate": "Engagement Rate",
    "dashboard.activeVsTotal": "Active users vs total",
    "dashboard.filter": "Filter",
    "dashboard.export": "Export",
    "dashboard.refresh": "Refresh",
    "dashboard.daily": "Daily",
    "dashboard.weekly": "Weekly",
    "dashboard.monthly": "Monthly",
    "dashboard.downloadReport": "Download Report",
    "dashboard.weeklyChart": "Weekly chart data would appear here",
    "dashboard.weeklyEngagement": "Weekly engagement data would appear here",
    "dashboard.monthlyChart": "Monthly chart data would appear here",
    "dashboard.monthlyEngagement": "Monthly engagement data would appear here",

    // Receipts
    receipts: "Receipts",
    "receipts.description": "Manage and view all customer receipts",
    "receipts.exportAll": "Export All",
    "receipts.searchReceipts": "Search receipts...",
    "receipts.dateRange": "Date Range",
    "receipts.filter": "Filter",
    "receipts.status": "Status",
    "receipts.allStatus": "All Status",
    "receipts.processed": "Processed",
    "receipts.pending": "Pending",
    "receipts.failed": "Failed",
    "receipts.receiptId": "Receipt ID",
    "receipts.customer": "Customer",
    "receipts.email": "Email",
    "receipts.date": "Date",
    "receipts.amount": "Amount",
    "receipts.items": "Items",
    "receipts.actions": "Actions",
    "receipts.showing": "Showing",
    "receipts.of": "of",
    "receipts.receipts": "receipts",
    "receipts.previous": "Previous",
    "receipts.next": "Next",

    // Customers
    customers: "Customers",
    "customers.description": "Manage your loyalty program customers",
    "customers.addCustomer": "Add Customer",
    "customers.searchCustomers": "Search customers...",
    "customers.customerId": "Customer ID",
    "customers.name": "Name",
    "customers.email": "Email",
    "customers.totalVisits": "Total Visits",
    "customers.pointsBalance": "Points Balance",
    "customers.tier": "Tier",
    "customers.joinDate": "Join Date",
    "customers.actions": "Actions",
    "customers.view": "View",
    "customers.showing": "Showing",
    "customers.of": "of",
    "customers.customers": "customers",
    "customers.previous": "Previous",
    "customers.next": "Next",
    "customers.bronze": "Bronze",
    "customers.silver": "Silver",
    "customers.gold": "Gold",

    // Loyalty Program
    loyalty: "Loyalty Program",
    "loyalty.description": "Configure your customer loyalty program",
    "loyalty.saveChanges": "Save Changes",
    "loyalty.rules": "Reward Rules",
    "loyalty.tiers": "Loyalty Tiers",
    "loyalty.redemption": "Redemption Options",
    "loyalty.pointsEarningRules": "Points Earning Rules",
    "loyalty.pointsEarningDescription": "Configure how customers earn points through purchases",
    "loyalty.pointsPerDollar": "Points per $1 spent",
    "loyalty.pointsPer": "points per $1",
    "loyalty.minPurchase": "Minimum purchase amount",
    "loyalty.bonusFirstPurchase": "Award bonus points for first purchase",
    "loyalty.bonusPoints": "bonus points",
    "loyalty.referralPoints": "Award points for referrals",
    "loyalty.pointsPerReferral": "points per referral",
    "loyalty.resetToDefault": "Reset to Default",
    "loyalty.saveRules": "Save Rules",
    "loyalty.pointsExpiration": "Points Expiration",
    "loyalty.expirationDescription": "Configure when earned points expire",
    "loyalty.enableExpiration": "Enable points expiration",
    "loyalty.expireAfter": "Points expire after",
    "loyalty.monthsInactivity": "months of inactivity",
    "loyalty.saveExpirationRules": "Save Expiration Rules",
    "loyalty.entryLevel": "Entry level tier",
    "loyalty.midTier": "Mid-tier level",
    "loyalty.premiumTier": "Premium tier level",
    "loyalty.qualificationThreshold": "Qualification Threshold",
    "loyalty.points": "points",
    "loyalty.pointsMultiplier": "Points Multiplier",
    "loyalty.standardRate": "x standard rate",
    "loyalty.birthdayBonus": "Birthday bonus",
    "loyalty.editBenefits": "Edit Benefits",
    "loyalty.addNewTier": "Add New Tier",
    "loyalty.standardDiscount": "Standard discount reward",
    "loyalty.pointsRequired": "Points Required",
    "loyalty.couponValidity": "Coupon Validity",
    "loyalty.days": "days",
    "loyalty.active": "Active",
    "loyalty.delete": "Delete",
    "loyalty.save": "Save",
    "loyalty.freeShipping": "Free Shipping",
    "loyalty.freeShippingDesc": "Free shipping on any order",
    "loyalty.percentOff": "10% Off Order",
    "loyalty.percentOffDesc": "Percentage discount on entire order",
    "loyalty.addNewReward": "Add New Reward",
    "loyalty.addRewardDesc": "Create a new redemption option for your customers",
    "loyalty.addReward": "Add Reward",
    "loyalty.level1": "Level 1",
    "loyalty.level2": "Level 2",
    "loyalty.level3": "Level 3",

    // Campaigns
    campaigns: "Campaigns",
    "campaigns.description": "Create and manage marketing campaigns",
    "campaigns.newCampaign": "New Campaign",
    "campaigns.searchCampaigns": "Search campaigns...",
    "campaigns.dateRange": "Date Range",
    "campaigns.filter": "Filter",
    "campaigns.export": "Export",
    "campaigns.campaignId": "Campaign ID",
    "campaigns.name": "Name",
    "campaigns.status": "Status",
    "campaigns.audience": "Audience",
    "campaigns.opens": "Opens",
    "campaigns.redemptions": "Redemptions",
    "campaigns.conversion": "Conversion",
    "campaigns.actions": "Actions",
    "campaigns.view": "View",
    "campaigns.showing": "Showing",
    "campaigns.of": "of",
    "campaigns.campaigns": "campaigns",
    "campaigns.previous": "Previous",
    "campaigns.next": "Next",
    "campaigns.active": "Active",
    "campaigns.scheduled": "Scheduled",
    "campaigns.ended": "Ended",
    "campaigns.performance": "Campaign Performance",
    "campaigns.performanceDesc": "Overview of your campaign metrics",
    "campaigns.viewAnalytics": "View Detailed Analytics",
    "campaigns.ideas": "Campaign Ideas",
    "campaigns.ideasDesc": "Suggested campaigns based on customer behavior",
    "campaigns.reengagement": "Re-engagement Campaign",
    "campaigns.reengagementDesc": "Target customers who haven't made a purchase in 30+ days",
    "campaigns.tierUpgrade": "Tier Upgrade Promotion",
    "campaigns.tierUpgradeDesc": "Encourage Bronze customers close to Silver tier to make additional purchases",
    "campaigns.referralBonus": "Referral Bonus",
    "campaigns.referralBonusDesc": "Offer double points for customer referrals this month",
    "campaigns.createNew": "Create New Campaign",

    // Analytics
    analytics: "Analytics",
    "analytics.description": "Detailed insights into your business performance",
    "analytics.dateRange": "Date Range",
    "analytics.filter": "Filter",
    "analytics.export": "Export",
    "analytics.overview": "Overview",
    "analytics.customers": "Customers",
    "analytics.sales": "Sales",
    "analytics.loyalty": "Loyalty",
    "analytics.last7days": "Last 7 days",
    "analytics.last30days": "Last 30 days",
    "analytics.last90days": "Last 90 days",
    "analytics.last12months": "Last 12 months",
    "analytics.revenueTrends": "Revenue Trends",
    "analytics.revenueDesc": "Daily revenue over time",
    "analytics.customerSegments": "Customer Segments",
    "analytics.segmentsDesc": "Distribution by tier",
    "analytics.purchaseFrequency": "Purchase Frequency",
    "analytics.frequencyDesc": "Visits per customer",
    "analytics.basketSize": "Average Basket Size",
    "analytics.basketDesc": "Average order value",
    "analytics.peakHours": "Peak Hours",
    "analytics.peakDesc": "Transaction volume by hour",

    // Settings
    settings: "Settings",
    "settings.description": "Manage your business settings and preferences",
    "settings.profile": "Business Profile",
    "settings.integrations": "Integrations",
    "settings.users": "User Management",
    "settings.notifications": "Notifications",
    "settings.businessInfo": "Business Information",
    "settings.businessInfoDesc": "Update your business details and contact information",
    "settings.businessName": "Business Name",
    "settings.businessEmail": "Business Email",
    "settings.businessPhone": "Business Phone",
    "settings.website": "Website",
    "settings.businessAddress": "Business Address",
    "settings.businessDescription": "Business Description",
    "settings.cancel": "Cancel",
    "settings.saveChanges": "Save Changes",
    "settings.branding": "Branding",
    "settings.brandingDesc": "Customize your loyalty program branding",
    "settings.programName": "Loyalty Program Name",
    "settings.logo": "Logo",
    "settings.changeLogo": "Change Logo",
    "settings.brandColors": "Brand Colors",
    "settings.change": "Change",
    "settings.apiKeys": "API Keys",
    "settings.apiKeysDesc": "Manage your API keys for integrations",
    "settings.apiKey": "API Key",
    "settings.regenerate": "Regenerate",
    "settings.apiKeyDesc": "This key allows access to your Receivt data via the API. Keep it secure.",
    "settings.connectedServices": "Connected Services",
    "settings.connectedServicesDesc": "Manage your connected third-party services",
    "settings.connectedOn": "Connected on",
    "settings.disconnect": "Disconnect",
    "settings.connectNew": "Connect a new service",
    "settings.connectNewDesc": "Add integration with other platforms",
    "settings.connect": "Connect",
    "settings.teamMembers": "Team Members",
    "settings.teamMembersDesc": "Manage your team members and their access",
    "settings.inviteUser": "Invite User",
    "settings.edit": "Edit",
    "settings.admin": "Admin",
    "settings.manager": "Manager",
    "settings.viewer": "Viewer",
    "settings.rolePermissions": "Role Permissions",
    "settings.rolePermissionsDesc": "Configure access levels for different user roles",
    "settings.fullAccess": "Full access to all features and settings",
    "settings.managerAccess": "Access to manage customers and loyalty program",
    "settings.viewerAccess": "Read-only access to dashboard and data",
    "settings.viewDashboard": "View Dashboard",
    "settings.manageCustomers": "Manage Customers",
    "settings.manageLoyalty": "Manage Loyalty Program",
    "settings.manageUsers": "Manage Users",
    "settings.emailNotifications": "Email Notifications",
    "settings.emailNotificationsDesc": "Configure which email notifications you receive",
    "settings.dailySummary": "Daily Summary",
    "settings.dailySummaryDesc": "Receive a daily summary of your business activity",
    "settings.newCustomerAlerts": "New Customer Alerts",
    "settings.newCustomerAlertsDesc": "Get notified when a new customer joins your loyalty program",
    "settings.campaignPerformance": "Campaign Performance",
    "settings.campaignPerformanceDesc": "Receive updates on your campaign performance",
    "settings.systemUpdates": "System Updates",
    "settings.systemUpdatesDesc": "Get notified about system updates and maintenance",
    "settings.resetToDefault": "Reset to Default",
    "settings.savePreferences": "Save Preferences",
    "settings.notificationRecipients": "Notification Recipients",
    "settings.notificationRecipientsDesc": "Configure who receives notifications",
    "settings.primaryEmail": "Primary Email",
    "settings.ccEmails": "CC Emails",
    "settings.ccEmailsDesc": "Separate multiple email addresses with commas",
    "settings.saveRecipients": "Save Recipients",

    // Sidebar
    "sidebar.dashboard": "Dashboard",
    "sidebar.receipts": "Receipts",
    "sidebar.customers": "Customers",
    "sidebar.loyaltyProgram": "Loyalty Program",
    "sidebar.campaigns": "Campaigns",
    "sidebar.analytics": "Analytics",
    "sidebar.settings": "Settings",
    "sidebar.logout": "Log out",
    "sidebar.language": "Language",
    "sidebar.english": "English",
    "sidebar.romanian": "Romanian",
  },
  ro: {
    // Language
    "language.select": "Română",

    // Dashboard
    dashboard: "Tablou de bord",
    "dashboard.description": "Prezentare generală a afacerii",
    "dashboard.totalCustomers": "Clienți loiali",
    "dashboard.receiptsProcessed": "Achiziții",
    "dashboard.pointsAwarded": "Puncte acordate",
    "dashboard.totalRevenue": "Venit total",
    "dashboard.vsPreviousMonth": "vs. luna precedentă",
    "dashboard.revenue": "Venit",
    "dashboard.revenueOverview": "Prin utilizarea aplicației",
    "dashboard.engagementRate": "Rata de angajament",
    "dashboard.activeVsTotal": "% utilizatori activi vs înregistrați",
    "dashboard.filter": "Filtrare",
    "dashboard.export": "Export",
    "dashboard.refresh": "Reîmprospătare",
    "dashboard.daily": "Zilnic",
    "dashboard.weekly": "Săptămânal",
    "dashboard.monthly": "Lunar",
    "dashboard.downloadReport": "Descarcă raport",
    "dashboard.weeklyChart": "Datele graficului săptămânal ar apărea aici",
    "dashboard.weeklyEngagement": "Datele de angajament săptămânal ar apărea aici",
    "dashboard.monthlyChart": "Datele graficului lunar ar apărea aici",
    "dashboard.monthlyEngagement": "Datele de angajament lunar ar apărea aici",
    "dashboard.seeMore": "Vezi mai mult",
    // Receipts
    receipts: "Chitanțe",
    "receipts.description": "Gestionați și vizualizați toate chitanțele clienților",
    "receipts.exportAll": "Exportă tot",
    "receipts.searchReceipts": "Caută chitanțe...",
    "receipts.dateRange": "Interval de date",
    "receipts.filter": "Filtrare",
    "receipts.status": "Stare",
    "receipts.allStatus": "Toate stările",
    "receipts.processed": "Procesat",
    "receipts.pending": "În așteptare",
    "receipts.failed": "Eșuat",
    "receipts.receiptId": "ID chitanță",
    "receipts.customer": "Client",
    "receipts.email": "Email",
    "receipts.date": "Data",
    "receipts.amount": "Sumă",
    "receipts.items": "Articole",
    "receipts.actions": "Acțiuni",
    "receipts.showing": "Se afișează",
    "receipts.of": "din",
    "receipts.receipts": "chitanțe",
    "receipts.previous": "Anterior",
    "receipts.next": "Următor",

    // Customers
    customers: "Clienți",
    "customers.description": "Gestionați clienții programului de fidelitate",
    "customers.addCustomer": "Adaugă client",
    "customers.searchCustomers": "Caută clienți...",
    "customers.customerId": "ID client",
    "customers.name": "Nume",
    "customers.email": "Email",
    "customers.totalVisits": "Total vizite",
    "customers.pointsBalance": "Sold puncte",
    "customers.tier": "Nivel",
    "customers.joinDate": "Data înscrierii",
    "customers.actions": "Acțiuni",
    "customers.view": "Vizualizare",
    "customers.showing": "Se afișează",
    "customers.of": "din",
    "customers.customers": "clienți",
    "customers.previous": "Anterior",
    "customers.next": "Următor",
    "customers.bronze": "Bronz",
    "customers.silver": "Argint",
    "customers.gold": "Aur",

    // Loyalty Program
    loyalty: "Program de fidelitate",
    "loyalty.description": "Configurați programul de fidelitate pentru clienți",
    "loyalty.saveChanges": "Salvează modificările",
    "loyalty.rules": "Reguli de recompensă",
    "loyalty.tiers": "Niveluri de fidelitate",
    "loyalty.redemption": "Opțiuni de răscumpărare",
    "loyalty.pointsEarningRules": "Reguli de câștigare a punctelor",
    "loyalty.pointsEarningDescription": "Configurați modul în care clienții câștigă puncte prin achiziții",
    "loyalty.pointsPerDollar": "Puncte per 1$ cheltuit",
    "loyalty.pointsPer": "puncte per 1$",
    "loyalty.minPurchase": "Suma minimă de achiziție",
    "loyalty.bonusFirstPurchase": "Acordă puncte bonus pentru prima achiziție",
    "loyalty.bonusPoints": "puncte bonus",
    "loyalty.referralPoints": "Acordă puncte pentru recomandări",
    "loyalty.pointsPerReferral": "puncte per recomandare",
    "loyalty.resetToDefault": "Resetare la implicit",
    "loyalty.saveRules": "Salvează regulile",
    "loyalty.pointsExpiration": "Expirarea punctelor",
    "loyalty.expirationDescription": "Configurați când expiră punctele câștigate",
    "loyalty.enableExpiration": "Activează expirarea punctelor",
    "loyalty.expireAfter": "Punctele expiră după",
    "loyalty.monthsInactivity": "luni de inactivitate",
    "loyalty.saveExpirationRules": "Salvează regulile de expirare",
    "loyalty.entryLevel": "Nivel de intrare",
    "loyalty.midTier": "Nivel mediu",
    "loyalty.premiumTier": "Nivel premium",
    "loyalty.qualificationThreshold": "Prag de calificare",
    "loyalty.points": "puncte",
    "loyalty.pointsMultiplier": "Multiplicator de puncte",
    "loyalty.standardRate": "x rata standard",
    "loyalty.birthdayBonus": "Bonus de ziua de naștere",
    "loyalty.editBenefits": "Editează beneficiile",
    "loyalty.addNewTier": "Adaugă nivel nou",
    "loyalty.standardDiscount": "Reducere standard",
    "loyalty.pointsRequired": "Puncte necesare",
    "loyalty.couponValidity": "Valabilitate cupon",
    "loyalty.days": "zile",
    "loyalty.active": "Activ",
    "loyalty.delete": "Șterge",
    "loyalty.save": "Salvează",
    "loyalty.freeShipping": "Livrare gratuită",
    "loyalty.freeShippingDesc": "Livrare gratuită pentru orice comandă",
    "loyalty.percentOff": "10% reducere la comandă",
    "loyalty.percentOffDesc": "Reducere procentuală pentru întreaga comandă",
    "loyalty.addNewReward": "Adaugă recompensă nouă",
    "loyalty.addRewardDesc": "Creați o nouă opțiune de răscumpărare pentru clienții dvs.",
    "loyalty.addReward": "Adaugă recompensă",
    "loyalty.level1": "Nivel 1",
    "loyalty.level2": "Nivel 2",
    "loyalty.level3": "Nivel 3",

    // Campaigns
    campaigns: "Campanii",
    "campaigns.description": "Creați și gestionați campanii de marketing",
    "campaigns.newCampaign": "Campanie nouă",
    "campaigns.searchCampaigns": "Caută campanii...",
    "campaigns.dateRange": "Interval de date",
    "campaigns.filter": "Filtrare",
    "campaigns.export": "Export",
    "campaigns.campaignId": "ID campanie",
    "campaigns.name": "Nume",
    "campaigns.status": "Stare",
    "campaigns.audience": "Audiență",
    "campaigns.opens": "Deschideri",
    "campaigns.redemptions": "Răscumpărări",
    "campaigns.conversion": "Conversie",
    "campaigns.actions": "Acțiuni",
    "campaigns.view": "Vizualizare",
    "campaigns.showing": "Se afișează",
    "campaigns.of": "din",
    "campaigns.campaigns": "campanii",
    "campaigns.previous": "Anterior",
    "campaigns.next": "Următor",
    "campaigns.active": "Activ",
    "campaigns.scheduled": "Programat",
    "campaigns.ended": "Încheiat",
    "campaigns.performance": "Performanța campaniei",
    "campaigns.performanceDesc": "Prezentare generală a metricilor campaniei",
    "campaigns.viewAnalytics": "Vizualizare analiză detaliată",
    "campaigns.ideas": "Idei de campanii",
    "campaigns.ideasDesc": "Campanii sugerate bazate pe comportamentul clienților",
    "campaigns.reengagement": "Campanie de reangajare",
    "campaigns.reengagementDesc": "Țintește clienții care nu au făcut o achiziție în ultimele 30+ zile",
    "campaigns.tierUpgrade": "Promoție de upgrade nivel",
    "campaigns.tierUpgradeDesc": "Încurajează clienții Bronz aproape de nivelul Argint să facă achiziții suplimentare",
    "campaigns.referralBonus": "Bonus de recomandare",
    "campaigns.referralBonusDesc": "Oferă puncte duble pentru recomandările clienților în această lună",
    "campaigns.createNew": "Creează campanie nouă",

    // Analytics
    analytics: "Analiză",
    "analytics.description": "Informații detaliate despre performanța afacerii dvs.",
    "analytics.dateRange": "Interval de date",
    "analytics.filter": "Filtrare",
    "analytics.export": "Export",
    "analytics.overview": "Prezentare generală",
    "analytics.customers": "Clienți",
    "analytics.sales": "Vânzări",
    "analytics.loyalty": "Fidelitate",
    "analytics.last7days": "Ultimele 7 zile",
    "analytics.last30days": "Ultimele 30 de zile",
    "analytics.last90days": "Ultimele 90 de zile",
    "analytics.last12months": "Ultimele 12 luni",
    "analytics.revenueTrends": "Tendințe de venit",
    "analytics.revenueDesc": "Venit zilnic în timp",
    "analytics.customerSegments": "Segmente de clienți",
    "analytics.segmentsDesc": "Distribuție pe niveluri",
    "analytics.purchaseFrequency": "Frecvența achizițiilor",
    "analytics.frequencyDesc": "Vizite per client",
    "analytics.basketSize": "Mărimea medie a coșului",
    "analytics.basketDesc": "Valoarea medie a comenzii",
    "analytics.peakHours": "Ore de vârf",
    "analytics.peakDesc": "Volumul tranzacțiilor pe oră",

    // Settings
    settings: "Setări",
    "settings.description": "Gestionați setările și preferințele afacerii dvs.",
    "settings.profile": "Profil afacere",
    "settings.integrations": "Integrări",
    "settings.users": "Gestionare utilizatori",
    "settings.notifications": "Notificări",
    "settings.businessInfo": "Informații afacere",
    "settings.businessInfoDesc": "Actualizați detaliile afacerii și informațiile de contact",
    "settings.businessName": "Nume afacere",
    "settings.businessEmail": "Email afacere",
    "settings.businessPhone": "Telefon afacere",
    "settings.website": "Website",
    "settings.businessAddress": "Adresă afacere",
    "settings.businessDescription": "Descriere afacere",
    "settings.cancel": "Anulare",
    "settings.saveChanges": "Salvează modificările",
    "settings.branding": "Branding",
    "settings.brandingDesc": "Personalizați brandingul programului de fidelitate",
    "settings.programName": "Nume program de fidelitate",
    "settings.logo": "Logo",
    "settings.changeLogo": "Schimbă logo",
    "settings.brandColors": "Culori brand",
    "settings.change": "Schimbă",
    "settings.apiKeys": "Chei API",
    "settings.apiKeysDesc": "Gestionați cheile API pentru integrări",
    "settings.apiKey": "Cheie API",
    "settings.regenerate": "Regenerare",
    "settings.apiKeyDesc": "Această cheie permite accesul la datele Receivt prin API. Păstrați-o în siguranță.",
    "settings.connectedServices": "Servicii conectate",
    "settings.connectedServicesDesc": "Gestionați serviciile terțe conectate",
    "settings.connectedOn": "Conectat pe",
    "settings.disconnect": "Deconectare",
    "settings.connectNew": "Conectați un serviciu nou",
    "settings.connectNewDesc": "Adăugați integrare cu alte platforme",
    "settings.connect": "Conectare",
    "settings.teamMembers": "Membri echipă",
    "settings.teamMembersDesc": "Gestionați membrii echipei și accesul lor",
    "settings.inviteUser": "Invită utilizator",
    "settings.edit": "Editare",
    "settings.admin": "Admin",
    "settings.manager": "Manager",
    "settings.viewer": "Vizualizator",
    "settings.rolePermissions": "Permisiuni roluri",
    "settings.rolePermissionsDesc": "Configurați nivelurile de acces pentru diferite roluri de utilizator",
    "settings.fullAccess": "Acces complet la toate funcțiile și setările",
    "settings.managerAccess": "Acces pentru gestionarea clienților și a programului de fidelitate",
    "settings.viewerAccess": "Acces doar pentru citire la tabloul de bord și date",
    "settings.viewDashboard": "Vizualizare tablou de bord",
    "settings.manageCustomers": "Gestionare clienți",
    "settings.manageLoyalty": "Gestionare program de fidelitate",
    "settings.manageUsers": "Gestionare utilizatori",
    "settings.emailNotifications": "Notificări email",
    "settings.emailNotificationsDesc": "Configurați ce notificări email primiți",
    "settings.dailySummary": "Rezumat zilnic",
    "settings.dailySummaryDesc": "Primiți un rezumat zilnic al activității afacerii dvs.",
    "settings.newCustomerAlerts": "Alerte clienți noi",
    "settings.newCustomerAlertsDesc": "Fiți notificat când un client nou se alătură programului de fidelitate",
    "settings.campaignPerformance": "Performanța campaniei",
    "settings.campaignPerformanceDesc": "Primiți actualizări despre performanța campaniei dvs.",
    "settings.systemUpdates": "Actualizări sistem",
    "settings.systemUpdatesDesc": "Fiți notificat despre actualizările și întreținerea sistemului",
    "settings.resetToDefault": "Resetare la implicit",
    "settings.savePreferences": "Salvează preferințele",
    "settings.notificationRecipients": "Destinatari notificări",
    "settings.notificationRecipientsDesc": "Configurați cine primește notificări",
    "settings.primaryEmail": "Email principal",
    "settings.ccEmails": "Emailuri CC",
    "settings.ccEmailsDesc": "Separați adresele de email multiple cu virgule",
    "settings.saveRecipients": "Salvează destinatarii",

    // Sidebar
    "sidebar.dashboard": "Tablou de bord",
    "sidebar.receipts": "Chitanțe",
    "sidebar.customers": "Clienți",
    "sidebar.loyaltyProgram": "Program de fidelitate",
    "sidebar.campaigns": "Campanii",
    "sidebar.analytics": "Analiză",
    "sidebar.settings": "Setări",
    "sidebar.logout": "Deconectare",
    "sidebar.language": "Limbă",
    "sidebar.english": "Engleză",
    "sidebar.romanian": "Română",
  },
}

// Create the provider component
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  // Load language preference from localStorage on component mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ro")) {
      setLanguageState(savedLanguage)
    }
  }, [])

  // Set language and save to localStorage
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

// Custom hook to use the language context
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
